spring:
  application:
    name: nivio
  main:
    lazy-initialization: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: <login user to smtp server>
    password: <login password to smtp server>
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true

logging:
  level:
    root: INFO
    de:
      bonndan:
        nivio:
          output: INFO

server:
  port: ${PORT:8080}

management:
  server:
    port: 8090

  endpoint:
    health:
      show-details: always

  health:
    mail:
      enabled: false

nivio:
  baseUrl: ${NIVIO_BASE_URL:}
  version: #project.version#
  pollingMilliseconds: 30000 # 30 secs
  # iconFolder: /a/local/path

---
spring:
  profiles: test

---
spring:
  profiles: local

server:
  port: 8080