spring:
  application:
    name: nivio

  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    show-sql: false
    hibernate.ddl-auto: update
    properties.hibernate.show_sql: false
    properties.hibernate.use_sql_comments: false
    properties.hibernate.format_sql: false

  datasource:
    url: jdbc:h2:/opt/nivio/database;DB_CLOSE_ON_EXIT=FALSE
    username: nivio
    password: nivio
    driver-class-name: org.h2.Driver

  mail:
    host: smtp.gmail.com
    port: 587
    username: <login user to smtp server>
    password: <login password to smtp server>
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true

logging:
  level:
    root: WARN
    org.hibnerate: debug

---
spring:
  profiles: test

  datasource.url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
  datasource.username: sa
  datasource.password: sa
  jpa.show-sql: true