spring:
  application:
    name: nivio
    
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    show-sql: true
    hibernate.ddl-auto: update
    properties.hibernate.show_sql: true
    properties.hibernate.use_sql_comments: false
    properties.hibernate.format_sql: false

  datasource:
    url: jdbc:h2:/opt/nivio/database;DB_CLOSE_ON_EXIT=FALSE
    username: nivio
    password: nivio
    driver-class-name: org.h2.Driver

  data:
    neo4j:
      username: neo4j
      password: test