spring:
  application:
    name: nivio

  mail:
    host: smtp.gmail.com
    port: 587
    username: <login user to smtp server>
    password: <login password to smtp server>
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true

logging:
  level:
    root: INFO

server:
  port: 8080

---
spring:
  profiles: test

  datasource.url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
  datasource.username: sa
  datasource.password: sa
  jpa.show-sql: true

---
spring:
  profiles: local

server:
  port: 8081