version: '3.2'

services:

  webserver:
    image: nginx
    ports:
      - 3000:80
    volumes:
      - ../src/test/resources/example:/usr/share/nginx/html:ro

  nivio:
    image: dedica/nivio:latest
    environment:
      # to provide the environment variables from the command line
      SEED: ${SEED}
      DEMO: ${DEMO}

      # enable DEMO to have a preloaded landscape
      # DEMO: 1

      # SEED also loads data, but uses the sources from the webserver
      # SEED: http://webserver:80/example_env.yml

      # SEED to load data from a local file, enable also volumes
      # SEED: /demo/dedica.yml
    # volumes:
      # - type: bind
        # source: ../src/test/resources/example
        # target: /demo
    ports:
      - 8080:8080
