name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.8
      - name: Test with Maven
        run: mvn test -B --file pom.xml
