name: Java CI

on:
  push:
    tags:
      - '*'
    branches:
      - master
      - develop
      - 107_deploy_heroku

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 11.0.4
    - name: Build with Maven
      run: mvn package --file pom.xml

    #
    # docker
    #
    - name: Build and Publish Docker latest
      if: github.ref != 'refs/heads/master'
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: dedica/nivio
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: "latest"

    - name: Build and Publish Docker stable
      if: github.ref == 'refs/heads/master'
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: dedica/nivio
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}


    # https://github.com/actions/heroku/issues/9
    - name: Heroku Release develop
      if: github.ref != 'refs/heads/master'
      run: |
        docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
        docker tag dedica/nivio:latest registry.heroku.com/nivio-demo/web
        docker push registry.heroku.com/nivio-demo/web
        heroku container:release web -a nivio-demo
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}