name: Java CI

on:
  push:
    tags:
      - '*'
    branches:
      - master
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 11.0.4
    - name: Build with Maven
      run: mvn package --file pom.xml
    - name: Build and Publish Docker
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: dedica-team/nivio
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Login to Heroku Container registry
      run: heroku container:login
      with:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
    - name: Build and push
      run: heroku container:push -a nivio-demo web
      with:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
    - name: Release
      run: heroku container:release -a nivio-demo web
      with:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
